/**
 * Registo de referências — porto direto de `referencias.md` (registo único
 * do projeto, ID estável por referência). Usado pela secção "Aprender" para
 * mostrar a citação completa ao expandir um ID, em vez de só o número.
 */
export interface Referencia {
  id: string;
  citacao: string;
  /** Fonte terciária/comercial ou citação incompleta, assinalada no registo original com ⚠️. */
  terciaria?: boolean;
}

const R = (id: string, citacao: string, terciaria = false): [string, Referencia] => [
  id,
  { id, citacao, terciaria },
];

export const REFERENCIAS: Record<string, Referencia> = Object.fromEntries([
  R("R01", "Bonkemeyer Millan S, Gan R, Townsend PE. Venous Ulcers: Diagnosis and Treatment. Am Fam Physician. 2019;100(5):298-305."),
  R("R02", "StatPearls [Internet]. Venous Leg Ulcer. NCBI Bookshelf."),
  R("R03", "O'Donnell TF Jr, Passman MA, Marston WA, et al. Management of venous leg ulcers: clinical practice guidelines of the Society for Vascular Surgery and the American Venous Forum. J Vasc Surg. 2014;60(2 Suppl):3S-59S."),
  R("R04", "Wounds UK. Arterial disease ulcers, part 1: clinical diagnosis and investigation."),
  R("R05", "Alagha M, et al. Review of Mixed Arterial Venous Leg Ulcers (MAVLU) Disease in Contemporary Practice. 2024."),
  R("R06", "Hedayati N, et al. Management of mixed arterial venous lower extremity ulceration: A review. 2015."),
  R("R07", "BC Provincial Nursing Skin and Wound Committee. Assessment and Treatment of Lower Leg Ulcers (Arterial, Venous & Mixed)."),
  R("R08", "Vohra Wound Care. Arterial Ulcer: Symptoms, Diagnosis, and Treatment. (blog comercial)", true),
  R("R09", "Endovascular Today. Ischemic and Venous Wound Identification.", true),
  R("R10", "Andriessen A, et al. Compression therapy for venous leg ulcers: risk factors for adverse events and complications, contraindications — a review of present guidelines. J Eur Acad Dermatol Venereol. 2017;31(9):1562-1568."),
  R("R11", "Rabe E, Partsch H, et al. Compression therapy for leg ulcers. (revisão, PMC)"),
  R("R12", "Wounds International. Principles of compression in venous disease."),
  R("R13", "Harrison MB, et al. The Canadian Bandaging Trial: evidence-informed leg ulcer care and the effectiveness of two compression technologies. BMC Health Serv Res. 2011;11:26."),
  R("R14", "European Pressure Ulcer Advisory Panel, National Pressure Injury Advisory Panel, Pan Pacific Pressure Injury Alliance. Prevention and Treatment of Pressure Ulcers/Injuries: Clinical Practice Guideline. Haesler E (ed). EPUAP/NPIAP/PPPIA, 2019."),
  R("R15", "Edsberg LE, et al. Revised National Pressure Ulcer Advisory Panel Pressure Injury Staging System. J Wound Ostomy Continence Nurs. 2016;43(6):585-597."),
  R("R16", "Mervis JS, Phillips TJ. Pressure ulcers: Pathophysiology, epidemiology, risk factors, and presentation. J Am Acad Dermatol. 2019;81(4):881-890."),
  R("R17", "Bus SA, et al. IWGDF Guideline on offloading foot ulcers in persons with diabetes and a foot ulcer, 2023 update. IWGDF/Diabetes Metab Res Rev."),
  R("R18", "Medscape. Diabetic Foot Ulcers: Clinical Presentation.", true),
  R("R19", "Raspovic A, Landorf KB. A survey of offloading practices for diabetes-related plantar neuropathic foot ulcers. J Foot Ankle Res. 2014;7:35."),
  R("R20", "American Diabetes Association. Standards of Care in Diabetes. Diabetes Care. (publicação anual — citar edição corrente)"),
  R("R21", "Fitridge R, Chuter V, Mills J, Hinchliffe R, et al. IWGDF/SVS Guideline on peripheral artery disease in patients with diabetes and a foot ulcer. J Vasc Surg. 2023;78(5):1101-1131."),
  R("R22", "Morbach S, et al. Peripheral Arterial Disease and the Diabetic Foot Syndrome: Neuropathy Makes the Difference! 2024."),
  R("R23", "Sandy-Hodgetts K, et al. Surgical wound dehiscence (SWD): International consensus statement on assessment, diagnosis and management. Wounds International."),
  R("R24", "Net Health. Wound Dehiscence: Guide for Providers.", true),
  R("R25", "Scoping Review 2024 sobre definição de deiscência de ferida cirúrgica na literatura.", true),
  R("R26", "CMAJ / Texas Children's Wound Care Guideline (gestão de feridas agudas/crónicas).", true),
  R("R27", "WCEI. Wound Care Basics: Types of Wounds.", true),
  R("R28", "Survey multicêntrico sobre classificação de feridas agudas em contexto de urgência, 2022.", true),
  R("R29", "EONS. Recommendations for the care of patients with malignant fungating wounds.", true),
  R("R30", "Nigrelli D, et al. Malignant fungating wounds assessment in palliative care: a scoping review. Front Public Health. 2025."),
  R("R31", "EWMA. Palliative Wound Care: Recommendations for the Management of Wound-related Symptoms. 2025.", true),
  R("R32", "NHS Forth Valley. Guidelines for the Management of Malignant Wounds (M:EMPHIS Pathway).", true),
  R("R33", "da Costa Santos CM, de Mattos Pimenta CA, Nobre MRC. A systematic review of topical treatments to control the odor of malignant fungating wounds. J Pain Symptom Manage. 2010;39(6):1065-76."),
  R("R34", "Palliative Care Network of Wisconsin. Managing Wound Odor. Fast Fact."),
  R("R35", "Kalinski C, et al. Effectiveness of a topical formulation containing metronidazole for wound odor and exudate control. J Wound Ostomy Continence Nurs. 2005;17(4):84-90."),
  R("R36", "Pharmacia Report. Managing Bleeding Fungating Wounds/Tumors.", true),
  R("R37", "Uso de Floseal em hemorragia de ferida fungante mamária — case report and literature review. PMC. 2024."),
  R("R38", "ScienceDirect Topics. Granulation Tissue.", true),
  R("R39", "StatPearls. Physiology, Granulation Tissue."),
  R("R40", "eCampusOntario. Tissue Types — Skin and Wound Care for Health Care Professionals. (recurso educativo)"),
  R("R41", "Skilled Wound Care. Tissue Types.", true),
  R("R42", "WRHA Wound Care. Tissue Types in Wound Bed. 2024. (guideline regional)"),
  R("R43", "Wounds UK. General Wound Care: Describing a wound. 2015."),
  R("R44", "WCEI. Exudate Wound Types: Serous, Sanguineous Drainage & More.", true),
  R("R45", "Osmosis. Serosanguineous: What Is It, Appearance, and More.", true),
  R("R46", "Net Health. Types of Drainage from Wounds: Provider's Guide.", true),
  R("R47", "Serigen Mediproducts. A Comprehensive Guide to Exudate Management in Wound Care.", true),
  R("R48", "Wound Care Advisor / WCEI. Causes, prevention, and treatment of epibole.", true),
  R("R49", "American Nurse Journal. Caring for chronic wounds: A knowledge update.", true),
  R("R50", "AHRQ. On-Time Pressure Ulcer Assessment (definições operacionais de bordos, ferramenta BWAT)."),
  R("R51", "Wounds International. Maceration in wound care: Towards a standardised assessment scale. 2026.", true),
  R("R52", "World Wide Wounds. Assessing and managing vulnerable periwound skin."),
  R("R53", "Dialogues in Wound Management. Periwound moisture-associated skin damage: An overview of etiology and management.", true),
  R("R54", "Wounds UK. The significance of the periwound in healing. 2025.", true),
  R("R55", "CMS/NPIAP. NPUAP Pressure Injury Stages (definições completas, 2016; nomenclatura NPIAP)."),
  R("R56", "Medline. Pressure injury stages: What they are and why they matter. 2026.", true),
  R("R57", "International Wound Infection Institute (IWII). Wound Infection in Clinical Practice: principles of best practice. Wounds International, 2022 update."),
  R("R58", "Swanson T, et al. IWII Wound Infection in Clinical Practice consensus document: 2022 update. J Wound Care. 2022;31(Sup12):S10."),
  R("R59", "Sibbald RG, et al. Increased bacterial burden and infection: NERDS and STONES. Wounds UK, 2009. (histórico — modelo anterior ao continuum IWII)"),
  R("R60", "Woo K, Sibbald RG. A cross-sectional validation study of using NERDS and STONEES to assess bacterial burden. Ostomy Wound Manage. 2009;55(8):40-8. (histórico)"),
  R("R61", "PMC. Wound debridement products and techniques.", true),
  R("R62", "StatPearls. Wound Debridement."),
  R("R63", "WCEI. Wound Debridement Basics.", true),
  R("R64", "eCampusOntario. Debridement Methods."),
  R("R65", "WCEI. Wound Care Dressings You Will Use Every Day.", true),
  R("R66", "StatPearls. Wound Dressings."),
  R("R67", "Weller CD, et al. First-line interactive wound dressing update: A comprehensive review of the evidence. J Tissue Viability / Int Wound J."),
  R("R68", "Wounds International. Development of silver resistance: A focus on wound care. 2025."),
  R("R69", "Totty JP, et al. Dialkylcarbamoyl chloride (DACC)-coated dressings in the management and prevention of wound infection: a systematic review. J Wound Care. 2017."),
  R("R70", "FDA. Executive Summary: Classification of Wound Dressings Combined with Drugs."),
  R("R71", "Wounds UK. Understanding the role of antimicrobial dressings."),
  R("R72", "Mavric E, et al. / Carter DA, et al. — trabalho sobre metilglioxal (MGO) e atividade antibacteriana do mel de Manuka."),
  R("R73", "Estudo sobre propriedades antibacterianas de pensos não tecidos revestidos com mel de Manuka/MGO.", true),
  R("R74", "Revisão sobre NPWT em cirurgia da coluna — mecanismos e evidência. PMC."),
  R("R75", "Revisão sistemática e meta-análise sobre NPWT em feridas de cicatrização por segunda intenção (ensaios controlados aleatorizados). PMC."),
  R("R76", "Wounds International. Negative pressure wound therapy — contemporary views on mechanisms of action (Kairinos et al., perfusão tecidual)."),
  R("R77", "ScienceDirect Topics. Negative Pressure Wound Therapy (contraindicações).", true),
  R("R78", "Management of Hypergranulation Tissue: A Report of a Pediatric Case. PMC."),
  R("R79", "Wound Care Advisor. How to apply silver nitrate.", true),
  R("R80", "CLWK (Clinical & Wound Care Knowledge, BC). Silver Nitrate (AgNO3) Sticks."),
  R("R81", "Maynell KB, et al. Utilization of Topical Polysporin and Triamcinolone for the Treatment of Hypergranulation Tissue. J Burn Care Res. 2024;45(3):669-674."),
  R("R82", "Use of Potent Topical Corticosteroids (TCS) for Hypergranulation Tissue (HGT) in Pediatric Patients. PMC."),
  R("R83", "'Magic Cream' — treats, no tricks: topical steroids for hypergranulation in burn wounds, retrospective review. ScienceDirect.", true),
  R("R84", "Linnemann PK, Litt J. Hypertrophic Granulation Wounds Treated With Silver Nitrate Sticks or With Topical Steroid: Rate of Wound Closure. J Burn Care Res. 2022;43(2):403-407."),
]);
